/* Generated by AN DISI Unibo */ 
package it.unibo.coldstorageservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Coldstorageservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "setup"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
					val MAXW = ColdStorageService.getMAXW()
					val TICKETTIME = ColdStorageService.getTICKETTIME()
				   	var currentWeightStorage = ColdStorageService.getCurrentWeightStorage()
				   	var requestWeightToStore = 0.0
				   	var TICKETNUMBER = ColdStorageService.getTicketNumber()
				   	val coldStorageServiceState = ColdStorageServiceState()
		    	  	
		return { //this:ActionBasciFsm
				state("setup") { //this:State
					action { //it:State
						CommUtils.outblue("$name |	setup")
						discardMessages = false
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						CommUtils.outblack("$name |	in idle")
						updateResourceRep(maxw.toJsonString() 
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="requestEvaluation",cond=whenRequest("storeFood"))
					transition(edgeName="t01",targetState="ticketEvaluation",cond=whenRequest("sendTicket"))
				}	 
				state("requestEvaluation") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("storeFood(FW)"), Term.createTerm("storeFood(FW)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblue("Request evaluation to store ${payloadArg(0)} kg")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="acceptRequest", cond=doswitchGuarded({ ColdStorageService.canStore(requestWeightToStore)  
					}) )
					transition( edgeName="goto",targetState="rejectRequest", cond=doswitchGuarded({! ( ColdStorageService.canStore(requestWeightToStore)  
					) }) )
				}	 
				state("acceptRequest") { //this:State
					action { //it:State
						
						    		var TICKET : Ticket = Ticket(TICKETNUMBER, TICKETTIME) 		
						    		ColdStorageService.getTicketList().add(TICKET)
						answer("storeFood", "storeAccepted", "storeAccepted(TICKETID)"   )  
						request("pickup", "pickup(TICKETID)" ,"transporttrolley" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleTicketExpired") { //this:State
					action { //it:State
						CommUtils.outred("$name |	ticket expired")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("rejectRequest") { //this:State
					action { //it:State
						answer("storeFood", "storeRejected", "storeRejected(_)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("dropout") { //this:State
					action { //it:State
						forward("dropout", "dropout(FW)" ,"transporttrolley" ) 
						forward("gotohome", "gotohome(_)" ,"transporttrolley" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("charged") { //this:State
					action { //it:State
						answer("deposit", "chargeTaken", "chargeTaken(_)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("ticketEvaluation") { //this:State
					action { //it:State
						CommUtils.outblue("Ticket evaluation of ticket id ${payloadArg(0)}")
						
						    	        		 val TICKETID = payloadArg(0).toInt()
						if( checkMsgContent( Term.createTerm("sendTicket(TICKETID)"), Term.createTerm("sendTicket($TICKETID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  ColdStorageService.evaluateTicket(TICKETID) == TicketEvaluationResponse.VALID  
								 ){answer("sendTicket", "ticketValid", "ticketValid(_)"   )  
								}
								if(  ColdStorageService.evaluateTicket(TICKETID) == TicketEvaluationResponse.INVALID  
								 ){answer("sendTicket", "ticketNotValid", "ticketNotValid(_)"   )  
								}
								answer("sendTicket", "ticketExpired", "ticketExpired(_)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
}
