/* Generated by AN DISI Unibo */ 
package it.unibo.basicrobotusage

import it.unibo.kactor.ActorBasicFsm
import it.unibo.kactor.Transition
import kotlinx.coroutines.CoroutineScope
import unibo.basicomm23.utils.CommUtils

class Basicrobotusage ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "ss0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 val Path    = "\"[w, w, l, w, w, w, w]\"" //Come quello restituito da dopath
				val MyName = name 
		return { //this:ActionBasciFsm
				state("ss0") { //this:State
					action { //it:State
						CommUtils.outblack("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().name} n=${Thread.activeCount()}")
						 	   
						request("engage", "engage(MyName)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="testDopath",cond=whenReply("engagedone"))
				}	 
				state("dowork") { //this:State
					action { //it:State
						request("step", "step(350)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t017",targetState="handleStepDone",cond=whenReply("stepdone"))
					transition(edgeName="t018",targetState="handleStepFail",cond=whenReply("stepfailed"))
				}	 
				state("handleStepDone") { //this:State
					action { //it:State
						CommUtils.outblack("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().name} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="dowork", cond=doswitch() )
				}	 
				state("handleStepFail") { //this:State
					action { //it:State
						CommUtils.outblack("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().name} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("testDopath") { //this:State
					action { //it:State
						request("dopath", "dopath($Path,$MyName,345)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t019",targetState="testDopathEnd",cond=whenReply("dopathdone"))
					transition(edgeName="t020",targetState="testDopathEnd",cond=whenReply("dopathfailed"))
				}	 
				state("testDopathEnd") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().name} n=${Thread.activeCount()}")
						 	   
						forward("disengage", "disengage($MyName)" ,"basicrobot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
}
