/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var CRX = 4;
				var CRY = 3;
				var INDOORX=0;
				var INDOORY=4;
				var HOMEX=0;
				var HOMEY=0;
				var TICKETID = 0;
				val tTState = transporttrolley.state.TransportTrolleyState()
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						discardMessages = false
						CommUtils.outred("$name | request engage")
						request("engage", "engage(transporttrolley,330)" ,"basicrobot" )  
						updateResourceRep(tTState.toJsonString() 
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="idle",cond=whenReply("engagedone"))
					transition(edgeName="t01",targetState="waitforfree",cond=whenReply("engagerefused"))
				}	 
				state("waitforfree") { //this:State
					action { //it:State
						CommUtils.outred("$name | already engaged")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("idle") { //this:State
					action { //it:State
						
									tTState.setCurrState(transporttrolley.state.CurrStateTrolley.IDLE)
									tTState.setCurrPosition(transporttrolley.state.TTPosition.HOME)
						updateResourceRep(tTState.toJsonString() 
						)
						CommUtils.outred("$name | waiting for commands.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="moverobottoindoor",cond=whenRequest("dodepositaction"))
				}	 
				state("moverobottoindoor") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("dodepositaction(TICKETID)"), Term.createTerm("dodepositaction(TICKETID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								 				TICKETID=payloadArg(0).toInt();
						}
						
									tTState.setCurrState(transporttrolley.state.CurrStateTrolley.PICKINGUP)
									tTState.setCurrPosition(transporttrolley.state.TTPosition.INDOOR)
						updateResourceRep(tTState.toJsonString() 
						)
						CommUtils.outred("$name | moving robot to indoor.")
						request("moverobot", "moverobot($INDOORX,$INDOORY)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t23",targetState="movetoport",cond=whenReply("moverobotdone"))
					transition(edgeName="t24",targetState="robotmovefailed",cond=whenReply("moverobotfailed"))
				}	 
				state("movetoport") { //this:State
					action { //it:State
						
									tTState.setCurrState(transporttrolley.state.CurrStateTrolley.MOVING)
									tTState.setCurrPosition(transporttrolley.state.TTPosition.ONTHEROAD)
						updateResourceRep(tTState.toJsonString() 
						)
						CommUtils.outred("$name | robot is in indoor")
						CommUtils.outred("$name | moving robot to coldroom")
						request("moverobot", "moverobot($CRX,$CRY)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t35",targetState="depositactionended",cond=whenReply("moverobotdone"))
					transition(edgeName="t36",targetState="robotmovefailed",cond=whenReply("moverobotfailed"))
				}	 
				state("depositactionended") { //this:State
					action { //it:State
						
									tTState.setCurrState(transporttrolley.state.CurrStateTrolley.DROPPINGOUT)
									tTState.setCurrPosition(transporttrolley.state.TTPosition.PORT)
						updateResourceRep(tTState.toJsonString() 
						)
						answer("dodepositaction", "depositactionended", "depositactionended($TICKETID)"   )  
						CommUtils.outred("$name | robot is in coldroom")
						CommUtils.outred("$name | depositaction ended")
						CommUtils.outred("$name | waiting for next move")
						emitlocal("local_dropoutdone", "local_dropoutdone" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_depositactionended", 
				 	 					  scope, context!!, "local_tout_transporttrolley_depositactionended", 100.toLong() )
					}	 	 
					 transition(edgeName="t47",targetState="robottohome",cond=whenTimeout("local_tout_transporttrolley_depositactionended"))   
					transition(edgeName="t48",targetState="moverobottoindoor",cond=whenRequest("dodepositaction"))
				}	 
				state("robottohome") { //this:State
					action { //it:State
						
									tTState.setCurrState(transporttrolley.state.CurrStateTrolley.MOVING)
									tTState.setCurrPosition(transporttrolley.state.TTPosition.ONTHEROAD)
						updateResourceRep(tTState.toJsonString() 
						)
						request("moverobot", "moverobot($HOMEX,$HOMEY)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t59",targetState="idle",cond=whenReply("moverobotdone"))
					transition(edgeName="t510",targetState="robotmovefailed",cond=whenReply("moverobotfailed"))
				}	 
				state("robotmovefailed") { //this:State
					action { //it:State
						CommUtils.outred("$name | robot failed to move")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
}
